version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      - node/install:
          node-version: latest

      - run: npm install autoprefixer

      - run: npm install postcss-cli

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # Set some variables to add to the commit message
      - run: git config --global user.email "noreply@example.com" && git config --global user.name "CircleCI Bot"

      # Build and push the generated files back to github
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

