version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build:
    # branches:
    #   ignore:
    #     - gh-pages
    docker:
       - image: felicianotech/docker-hugo:0.21
    #  - image: cibuilds/hugo:latest
    # working_directory: ~/hugo
    # environment:
    #   HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # checkout the repository
      - checkout

      #- node/install:
      #    node-version: latest

      #- run: npm install -D --save autoprefixer

      #- run: npm install -D --save postcss-cli

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # Set some variables to add to the commit message
      - run: git config --global user.email "noreply@example.com" && git config --global user.name "CircleCI Bot"

      # Build and push the generated files back to github
      - run: hugo

